# Generated by Django 2.2 on 2022-02-28 07:24

from django.db import migrations


def create_base_products(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Product = apps.get_model('products', 'Product')
    p = Product(name="apple", stockpile=17, price=1.0).save()
    p = Product(name="orange", stockpile=8, price=2.0).save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_base_products),
    ]
