# Generated by Django 2.2 on 2022-02-28 07:30

from django.db import migrations


def create_base_sells(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Sell = apps.get_model('sells', 'Sell')
    Product = apps.get_model('products', 'Product')
    s1 = Sell(client_name="Dupond", quantity=10)
    p1 = Product.objects.filter(id=1).first()
    s1.product = p1
    s1.unit_price = p1.price
    s1.save()
    
    s2 = Sell(client_name="Dupont", quantity=15)
    p2 = Product.objects.filter(id=2).first()
    s2.product = p2
    s2.unit_price = p2.price
    s2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_base_sells),
    ]
