# Generated by Django 2.2 on 2022-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price', models.FloatField(default=0)),
                ('stockpile', models.IntegerField(default=0)),
            ],
        ),
    ]
